name: Initialize GitHub repository with protected branches

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: "Enter the name of a repository you want to create"
        required: true
        
env:
  TF_VAR_gh_token: ${{ secrets.ACCESS_TOKEN }}
  TF_VAR_repo_name: ${{ inputs.repoName }}

defaults:
  run:
    working-directory: git-init-repo

jobs:
  Terraform-Script:
    runs-on: ubuntu-latest
    name: Terraform Repo Initalization Script

    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      
      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initializing Terraform
        id: init
        run: terraform init

      - name: Validating Configuration
        id: validate
        run: terraform validate -no-color

      - name: Staging Terraform Changes
        id: plan
        run: terraform plan -no-color

      - name: Echoing POST request headers
        run: |
          # Make a POST request to the GitHub API
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"key": "value"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.run_id }}/dispatches)

          # Dump the response contents to the workflow logs
          echo "Response Contents: $response"
          
      - name: Creating Repo via Terraform
        id: apply
        run: terraform apply -auto-approve