name: Read Secret

on:
    workflow_dispatch:

jobs:
    Secret-Script:
        permissions: write-all
        runs-on: ubuntu-latest
        name: Secret Read test

        steps:
        -   name: Check out code
            uses: actions/checkout@v4
        
        -   name: Show secret via python
            env:
                val: ${{ secrets.ACCESS_TOKEN }}
            run: |
                import os
                for q in (os.getenv("val")):
                    print(q)
            shell: python
        
        -   name: Show secret via SED
            run: echo ${{ secrets.ACCESS_TOKEN }} | sed 's/./& /g'
            