name: Initialize GitHub repository with protected branches

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: "Enter the name of a repository you want to create"
        required: true
      repoDesc:
        description: "Enter a description for the repository"
        required: false
        default: "Repository Created with Terraform"
        
env:
  TF_VAR_gh_token: ${{ secrets.ACCESS_TOKEN }}
  TF_VAR_repo_name: ${{ inputs.repoName }}
  TF_VAR_repo_description: ${{ inputs.repoDesc }}

defaults:
  run:
    working-directory: git-init-repo

jobs:
  Terraform-Script:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Terraform Repo Initalization Script

    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      
      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initializing Terraform
        id: init
        run: terraform init

      - name: Validating Configuration
        id: validate
        run: terraform validate -no-color

      - name: Staging Terraform Changes
        id: plan
        run: terraform plan -no-color

      - name: Creating Repo via Terraform
        id: apply
        env:
          TF_VAR_gh_token: ${{ secrets.ACCESS_TOKEN }}
        run: terraform apply -auto-approve
